name: "4EVERLAND ipfs upload"
description: "Upload folder to ipfs"
inputs:
  BUILD_LOCATION:
    description: "Folder path to upload"
    required: true
  EVER_TOKEN:
    description: "4EVERLAND token"
    required: true
  EVER_PROJECT_ID:
    description: "4EVERLAND hosting project id"
    required: false
  EVER_PROJECT_NAME:
    description: "4EVERLAND hosting project name"
    required: false
  EVER_PROJECT_PLAT:
    description: "4EVERLAND hosting project platform"
    required: false
  PULL_REQUEST_NUMBER:
    description: "Github pull request number"
    required: false
  GITHUB_TOKEN:
    description: "Github token"
    required: false

outputs:
  hash:
    description: "The ipfs hash"
  uri:
    description: "A uri embeddign the hash in a public gateway"
  projLink:
    description: "The project link on 4everland"
runs:
  using: "node16"
  main: "dist/index.js"
